### ISSUE TITLE
Error when creating a public signer for certificates

### ISSUE THREAD

**Issue by Joebayld** [vapor/jwt#123]
Looking at old commits (pre v4) there was added support for certificates. Is this in version 4? 

I'm trying to use these google certs:
https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com 

With this code: (ignore the hard code for testing!) 
```
let publicKey = certs["f5c9aebe234da6016bd7b949168b8cd5b4ec9eeb"]!
let publicSigner = try JWTSigner.rs256(key: .public(pem: publicKey.bytes))
```

I get the following error when creating a public signer. 
`Fatal error: Error raised at top level: JWTKit error: signing algorithm error: bioConversionFailure: file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.8.25.8/swift/stdlib/public/core/ErrorType.swift, line 200
2020-05-16 20:07:25.947242-0700 Run[9217:3171678] Fatal error: Error raised at top level: JWTKit error: signing algorithm error: bioConversionFailure: file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.8.25.8/swift/stdlib/public/core/ErrorType.swift, line 200`

Thanks!

**Comment by gwynne** [comment]
This appears to be due to passing an X.509 certificate (a PEM blob starting with `------ BEGIN CERTIFICATE ------` or very similar) to the public key initializer for RS256, which invokes `PEM_read_bio_PUBKEY()` - the `PUBKEY` variant  expects a PKCS#8 public key (PEM blob starting with `------ BEGIN PUBLIC KEY ------`, wrapping a `SubjectPublicKeyInfo` tagged as `rsaEncryption` and in turn containing an `RSAPublicKey`). While an X.509v3 certificate does indeed _contain_ a public key, it unfortunately can not be directly parsed as if it were one.

`JWTKit` should provide a `.public(x509:)` convenience utility, since extracting a certificate's public key in PKCS#8 PEM form is either a ridiculous ring-around-the-rosy using NIOSSL, or else just painful using BoringSSL directly. However, this is not a bug as such.

**Comment by ezfe** [comment]
Just wanted to drop in and say that this issue occurred for me due to the lack of newlines, as I was trying to pass it in through an environment variable. When I added them back in, this issue went away.

**Comment by abesmon** [comment]
Just message for future developers: jWTKit now providing x509 initialization thru `.certificate(pem: cert)`

**Comment by ios-apps** [comment]
I used .replacingOccurrences(of: "\\n", with:  "\n") after private key reading from  .env

**Comment by rafaelclaycon** [comment]
Heads up to devs sending push notifications through their servers and omitting the Apple ECP8 Private Key from their code because they made the project public and don't want the key revealed: JWT will scream at you if it doesn't see a proper key passed
```
func configurePush() throws {
        let appleECP8PrivateKey =
        """
        -----BEGIN PRIVATE KEY-----
           <--- HERE!
        -----END PRIVATE KEY-----
        """
        
        apns.configuration = try .init(
            authenticationMethod: .jwt(
                key: .private(pem: Data(appleECP8PrivateKey.utf8)),
                keyIdentifier: "",
                teamIdentifier: ""
            ),
            topic: "com.rafaelschmitt.MyApp",
            environment: .production
        )
    }
```
Just comment this code out while you test.
