### ISSUE TITLE
Missing ECDSASigner to support ES256 …

### ISSUE THREAD

**Issue by Kireyin** [vapor/jwt#92]
ECDSA algorithms haven't been implemented yet. ES256 algorithm is needed to generate JWT for Apple service such as MapKit JS and MusicKit.

**Comment by tanner0101** [comment]
This requires proper ECDSA support in vapor/crypto. I've created an issue here: https://github.com/vapor/crypto/issues/73.

**Comment by dylanreich** [comment]
Any update on this, or anyone know of any packages that provide ES256?

**Comment by tanner0101** [comment]
@dylanreich vapor/crypto#73 will probably be fixed in the next major release. OpenSSL, which is a dependency of vapor/crypto and thus vapor/jwt, has methods for doing ECDSA already. They just require some work to use. You can see an example of this here: https://github.com/moritzsternemann/nio-apns/tree/master/Sources/NIOAPNS/Crypto

**Comment by tanner0101** [comment]
JWTKit 4.0.0 supports ECDSA 👍
